### ISSUE TITLE
CurseForge&Modrinth?

### ISSUE THREAD

**Issue by Kasualix** [TomatoPuddin/PlayerNameTweaks#1]
有意向把模组文件上传到curseforge和modrinth上吗？

**Comment by TomatoPuddin** [comment]
这周内吧，有时间了就传

**Comment by TomatoPuddin** [comment]
[https://www.curseforge.com/minecraft/mc-mods/player-name-tweaks](url)
在审核

**Comment by TomatoPuddin** [comment]
已通过审核
